sudo: required
services:
    - docker

before_install:
    - docker build -t captainslow/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true captainslow/react-test npm test

after_success:
    - docker build -t captainslow/multi-client ./client
    - docker build -t captainslow/multi-nginx ./nginx
    - docker build -t captainslow/multi-server ./server
    - docker build -t captainslow/multi-worker ./worker

    # Log in to the Docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    # take these images and push them to Docker hub
    - docker push captainslow/multi-client
    - docker push captainslow/multi-nginx
    - docker push captainslow/multi-server
    - docker push captainslow/multi-worker
